// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

type ObjectType int64

const (
	ObjectTypeUnknown ObjectType = 0
	ObjectTypeMenu    ObjectType = 1
)

func (o ObjectType) String() string {
	switch o {
	case ObjectTypeMenu:
		return "menu"
	case ObjectTypeUnknown:
		return "unknown"
	default:
		return ""
	}
}

func (o ObjectType) IsValid() bool {
	switch o {
	case ObjectTypeMenu:
		return true
	default:
		return false
	}
}

const TableNameTblObject = "tbl_object"

// TblObject tbl_object
type TblObject struct {
	Id         int64       `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                                                                                    // id
	Type       ObjectType  `gorm:"column:type;type:int;not null;index:idx_object_type_deleted_status,priority:1;comment:type" json:"type"`                                                            // type
	Code       string      `gorm:"column:code;type:varchar(100);not null;uniqueIndex:uk_object_code,priority:1;comment:code" json:"code"`                                                             // code
	Name       string      `gorm:"column:name;type:varchar(100);not null;index:idx_object_name,priority:1;comment:name" json:"name"`                                                                  // name
	ParentCode string      `gorm:"column:parent_code;type:varchar(100);not null;index:idx_object_parent_deleted_status,priority:1;comment:parent_code" json:"parent_code"`                            // parent_code
	Sort       int64       `gorm:"column:sort;type:int;not null;comment:sort" json:"sort"`                                                                                                            // sort
	Status     int64       `gorm:"column:status;type:int;not null;index:idx_object_parent_deleted_status,priority:3;index:idx_object_type_deleted_status,priority:3;comment:status" json:"status"`    // status
	Deleted    DeletedFlag `gorm:"column:deleted;type:int;not null;index:idx_object_parent_deleted_status,priority:2;index:idx_object_type_deleted_status,priority:2;comment:deleted" json:"deleted"` // deleted
	CreatedAt  time.Time   `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"`                                                           // created_at
	UpdatedAt  time.Time   `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"`                                                           // updated_at
}

// TableName TblObject's table name
func (*TblObject) TableName() string {
	return TableNameTblObject
}
