// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTblCasbinRule = "tbl_casbin_rule"

// TblCasbinRule tbl_casbin_rule
type TblCasbinRule struct {
	Id    int64  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                                                                                                      // id
	Ptype string `gorm:"column:ptype;type:varchar(10);not null;uniqueIndex:uk_casbin_policy,priority:1;index:idx_casbin_ptype_v0,priority:1;index:idx_casbin_ptype_v1,priority:1;comment:ptype" json:"ptype"` // ptype
	V0    string `gorm:"column:v0;type:varchar(100);not null;uniqueIndex:uk_casbin_policy,priority:2;index:idx_casbin_ptype_v0,priority:2;comment:v0" json:"v0"`                                              // v0
	V1    string `gorm:"column:v1;type:varchar(100);not null;uniqueIndex:uk_casbin_policy,priority:3;index:idx_casbin_ptype_v1,priority:2;comment:v1" json:"v1"`                                              // v1
	V2    string `gorm:"column:v2;type:varchar(100);not null;uniqueIndex:uk_casbin_policy,priority:4;comment:v2" json:"v2"`                                                                                   // v2
	V3    string `gorm:"column:v3;type:varchar(100);not null;uniqueIndex:uk_casbin_policy,priority:5;comment:v3" json:"v3"`                                                                                   // v3
	V4    string `gorm:"column:v4;type:varchar(100);not null;uniqueIndex:uk_casbin_policy,priority:6;comment:v4" json:"v4"`                                                                                   // v4
	V5    string `gorm:"column:v5;type:varchar(100);not null;uniqueIndex:uk_casbin_policy,priority:7;comment:v5" json:"v5"`                                                                                   // v5
}

// TableName TblCasbinRule's table name
func (*TblCasbinRule) TableName() string {
	return TableNameTblCasbinRule
}
