// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTblMenu = "tbl_menu"

// TblMenu tbl_menu
type TblMenu struct {
	Id         int64     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                                            // id
	Code       string    `gorm:"column:code;type:varchar(255);not null;uniqueIndex:uk_menu_code,priority:1;comment:code" json:"code"`                       // code
	Name       string    `gorm:"column:name;type:varchar(255);not null;comment:name" json:"name"`                                                           // name
	ParentCode string    `gorm:"column:parent_code;type:varchar(255);index:idx_menu_parent_sort_deleted,priority:1;comment:parent_code" json:"parent_code"` // parent_code
	Sort       int64     `gorm:"column:sort;type:int;not null;index:idx_menu_parent_sort_deleted,priority:2;comment:sort" json:"sort"`                      // sort
	Url        string    `gorm:"column:url;type:varchar(255);comment:url" json:"url"`                                                                       // url
	Status     int64     `gorm:"column:status;type:tinyint;not null;comment:status" json:"status"`                                                          // status
	Visible    int64     `gorm:"column:visible;type:tinyint;not null;comment:visible" json:"visible"`                                                       // visible
	Deleted    int64     `gorm:"column:deleted;type:tinyint;not null;index:idx_menu_parent_sort_deleted,priority:3;comment:deleted" json:"deleted"`         // deleted
	CreatedAt  time.Time `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"`                   // created_at
	UpdatedAt  time.Time `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"`                   // updated_at
}

// TableName TblMenu's table name
func (*TblMenu) TableName() string {
	return TableNameTblMenu
}
