// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

type SubjectType int64

const (
	SubjectTypeUnknown SubjectType = 0
	SubjectTypeUser    SubjectType = 1 // user
	SubjectTypeRole    SubjectType = 2 // role
)

func (s SubjectType) String() string {
	switch s {
	case SubjectTypeUser:
		return "user"
	case SubjectTypeRole:
		return "role"
	case SubjectTypeUnknown:
		return "unknown"
	default:
		return ""
	}
}

func (s SubjectType) IsValid() bool {
	switch s {
	case SubjectTypeUser, SubjectTypeRole:
		return true
	default:
		// 包含 SubjectTypeUnknown (0) 和所有其他非法数字
		return false
	}
}

const TableNameTblSubject = "tbl_subject"

// TblSubject mapped from table <tbl_subject>
type TblSubject struct {
	Id         int64       `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                                                                                      // id
	Type       SubjectType `gorm:"column:type;type:int;not null;index:idx_subject_type_deleted_status,priority:1;comment:type" json:"type"`                                                             // type
	Code       string      `gorm:"column:code;type:varchar(100);not null;uniqueIndex:uk_subject_code,priority:1;comment:code" json:"code"`                                                              // code
	Name       string      `gorm:"column:name;type:varchar(100);not null;index:idx_subject_name,priority:1;comment:name" json:"name"`                                                                   // name
	ParentCode string      `gorm:"column:parent_code;type:varchar(100);not null;index:idx_subject_parent_deleted_status,priority:1;comment:parent_code" json:"parent_code"`                             // parent_code
	Sort       int64       `gorm:"column:sort;type:int;not null;comment:sort" json:"sort"`                                                                                                              // sort
	Status     int64       `gorm:"column:status;type:int;not null;index:idx_subject_parent_deleted_status,priority:3;index:idx_subject_type_deleted_status,priority:3;comment:status" json:"status"`    // status
	Deleted    DeletedFlag `gorm:"column:deleted;type:int;not null;index:idx_subject_parent_deleted_status,priority:2;index:idx_subject_type_deleted_status,priority:2;comment:deleted" json:"deleted"` // deleted
	CreatedAt  time.Time   `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:created_at" json:"created_at"`                                                             // created_at
	UpdatedAt  time.Time   `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:updated_at" json:"updated_at"`                                                             // updated_at
}

// TableName TblSubject's table name
func (*TblSubject) TableName() string {
	return TableNameTblSubject
}
